-- gfm-ids.lua: Make pandoc generate GitHub-style heading IDs that
-- preserve leading numbers.  The book's TOC is generated by
-- scripts/book-toc.py which uses github-slugger rules.  Pandoc's
-- default auto_identifiers strip leading digits, breaking every
-- numbered-subsection link (e.g. ## 8.10 The voice -> #the-voice
-- instead of #810-the-voice).
--
-- This filter reproduces the exact github-slugger algorithm so the
-- heading IDs match the TOC anchors.  Python's \w is ASCII-only
-- in the TOC generator, so we must also strip non-ASCII here.

local seen = {}

function Header(el)
  -- Get the rendered text of the heading
  local text = pandoc.utils.stringify(el)

  -- Step 1: lowercase
  local id = text:lower()

  -- Step 2: strip non-ASCII bytes (§, em-dash, curly quotes, etc.)
  -- Python's re \w with no UNICODE flag matches [a-zA-Z0-9_] only,
  -- and the TOC generator uses that.  Match it exactly.
  id = id:gsub("[\128-\255]", "")

  -- Step 3: strip everything except ASCII word chars, hyphens, spaces
  -- This matches Python's [^\w\- ] with ASCII \w = [a-zA-Z0-9_]
  id = id:gsub("[^%a%d_% %-]", "")

  -- Step 4: spaces to hyphens
  id = id:gsub(" ", "-")

  -- NOTE: do NOT collapse multiple hyphens or strip leading/trailing
  -- ones.  Python's github-slugger in book-toc.py does not, and the
  -- IDs must match exactly.  "MCP – The" -> "mcp--the" (two hyphens).

  -- De-duplicate exactly like github-slugger
  local base = id
  if seen[id] then
    seen[base] = seen[base] + 1
    id = base .. "-" .. seen[base]
  end
  if not seen[id] then
    seen[id] = 0
  end

  el.identifier = id
  return el
end
